# Generated by Django 6.0.3 on 2026-04-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='remarks',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
