# Generated by Django 6.0.4 on 2026-04-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller')], max_length=30),
        ),
    ]
