# Generated by Django 6.0.4 on 2026-04-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_contact_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Beller', 'Seller')], max_length=30),
        ),
    ]
