# Generated by Django 6.0.4 on 2026-04-14 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('gearless', 'gearless'), ('3_gears', '3_gears'), ('6_gears', '6_gears')], max_length=30)),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.PositiveIntegerField()),
                ('product_image', models.ImageField(upload_to='product_image/')),
                ('product_desc', models.TextField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
