# Generated by Django 6.0.3 on 2026-04-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=20)),
                ('mobile', models.PositiveIntegerField()),
                ('profile_picture', models.ImageField(upload_to='profile_picture/')),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
